Fix bug in a2high test

diff --git a/tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue-onspot.yaml b/tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue-onspot.yaml
--- a/tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue-onspot.yaml
+++ b/tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue-onspot.yaml
@@ -40,9 +40,6 @@ steps:
   - "ANSIBLE_CONFIG=/workspace/tools/cloud-build/ansible.cfg"
   - "PROJECT_ID=$PROJECT_ID"
   - "NUM_NODES=12"
-  - "MIN_NODES=6"
-  - "ZONE=us-central1-b"
-  - "PROVISIONING_MODEL=SPOT"
   - "MACHINE_TYPE=a2-highgpu-2g"
   - "INSTANCE_PREFIX=a2hspgke"
   - "BUILD_ID=$BUILD_ID"
@@ -52,13 +49,12 @@ steps:
   - -c
   - |
     set -e -u -o pipefail
-    # Commenting out dynamically setting zone due to test failures.
-    # echo "Sourcing find_available_zone.sh to determine zone."
-    # source /workspace/tools/cloud-build/find_available_zone.sh
-    # if [ -z "$${ZONE:-}" ]; then
-    #   echo "ERROR: ZONE not found" >&2
-    #   exit 1
-    # fi
+    echo "Sourcing find_available_zone.sh to determine zone."
+    source /workspace/tools/cloud-build/find_available_zone.sh
+    if [ -z "$${ZONE:-}" ]; then
+      echo "ERROR: ZONE not found" >&2
+      exit 1
+    fi
     REGION="$${ZONE%-*}"
     echo "Using ZONE=$${ZONE} and REGION=$${REGION}"
 
